# Form implementation generated from reading ui file 'C:\Users\CHO\toicProject\hun\toicPojectSH\member\loginPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class LogInUI(object):
    def setupUi(self, loginPage):
        loginPage.setObjectName("loginPage")
        loginPage.resize(360, 600)
        loginPage.setStyleSheet("background-color:rgb(255, 255, 255)\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=loginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.loginBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.loginBtn.setGeometry(QtCore.QRect(60, 420, 240, 40))
        self.loginBtn.setStyleSheet("background-color:rgb(255, 240, 129)")
        self.loginBtn.setObjectName("loginBtn")
        self.toRegisterPageBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.toRegisterPageBtn.setGeometry(QtCore.QRect(60, 470, 240, 40))
        self.toRegisterPageBtn.setStyleSheet("background-color:rgb(239, 239, 239)")
        self.toRegisterPageBtn.setObjectName("toRegisterPageBtn")
        self.id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id.setGeometry(QtCore.QRect(60, 310, 240, 40))
        self.id.setObjectName("id")
        self.password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.password.setGeometry(QtCore.QRect(60, 360, 240, 40))
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 265, 190, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 700 22pt;")
        self.label.setObjectName("label")

        self.dogImage = QtWidgets.QLabel(self.centralwidget)
        self.dogImage.setGeometry(QtCore.QRect(75, 70, 220, 180))
        self.dogImage.setPixmap(QtGui.QPixmap(f"service/UI/image/dog_level5.png"))
        self.dogImage.setObjectName("dogImage")
        self.dogImage.setScaledContents(True)
        self.dogImage.raise_()  # 이미지를 맨 앞으로 가져옴

        loginPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=loginPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 33))
        self.menubar.setObjectName("menubar")
        loginPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=loginPage)
        self.statusbar.setObjectName("statusbar")
        loginPage.setStatusBar(self.statusbar)

        self.retranslateUi(loginPage)
        QtCore.QMetaObject.connectSlotsByName(loginPage)

    def retranslateUi(self, loginPage):
        _translate = QtCore.QCoreApplication.translate
        loginPage.setWindowTitle(_translate("loginPage", "MainWindow"))
        self.loginBtn.setText(_translate("loginPage", "로그인"))
        self.toRegisterPageBtn.setText(_translate("loginPage", "회원가입"))
        self.id.setText(_translate("loginPage", "아이디"))
        self.password.setText(_translate("loginPage", "비밀번호"))
        self.label.setText(_translate("loginPage", "토익멍 기르기"))

