# Form implementation generated from reading ui file 'my_page_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MyPageUI(object):
    def setupUi(self, MyPageUI, user):
        self.user = user

        MyPageUI.setObjectName("MyPageUI")
        MyPageUI.resize(360, 600)
        MyPageUI.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=MyPageUI)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 270, 361, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_4.setStyleSheet("border: 0px")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.set_goal_button = QtWidgets.QPushButton(parent=self.frame_4)
        self.set_goal_button.setGeometry(QtCore.QRect(8, 10, 341, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.set_goal_button.sizePolicy().hasHeightForWidth())
        self.set_goal_button.setSizePolicy(sizePolicy)
        self.set_goal_button.setStyleSheet("background-color: rgb(255, 230, 130);")
        self.set_goal_button.setObjectName("set_goal_button")
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_6 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_6.setStyleSheet("border: 0px")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.wrong_note_button = QtWidgets.QPushButton(parent=self.frame_6)
        self.wrong_note_button.setGeometry(QtCore.QRect(8, 10, 341, 71))
        self.wrong_note_button.setStyleSheet("background-color: rgb(255, 230, 130)")
        self.wrong_note_button.setObjectName("wrong_note_button")
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_5 = QtWidgets.QFrame(parent=self.verticalLayoutWidget)
        self.frame_5.setStyleSheet("border: 0px")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.bookmark_note_button = QtWidgets.QPushButton(parent=self.frame_5)
        self.bookmark_note_button.setGeometry(QtCore.QRect(8, 10, 341, 71))
        self.bookmark_note_button.setStyleSheet("background-color: rgb(255, 230, 130)")
        self.bookmark_note_button.setObjectName("bookmark_note_button")
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 360, 60))
        self.frame_2.setStyleSheet("background-color: rgba(253, 213, 51, 0.97)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setObjectName("back_button")
        self.horizontalLayout.addWidget(self.back_button)
        self.menu_name_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_name_label.sizePolicy().hasHeightForWidth())
        self.menu_name_label.setSizePolicy(sizePolicy)
        self.menu_name_label.setStyleSheet("font: 24px bold;\n"
"qproperty-alignment: \'AlignCenter\';\n"
"text-align: center")
        self.menu_name_label.setObjectName("menu_name_label")
        self.horizontalLayout.addWidget(self.menu_name_label)
        self.home_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        self.home_button.setObjectName("home_button")
        self.horizontalLayout.addWidget(self.home_button)
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 361, 211))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.logout_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.logout_button.setGeometry(QtCore.QRect(240, 40, 81, 31))
        self.logout_button.setStyleSheet("background-color: rgb(224, 224, 224)")
        self.logout_button.setObjectName("logout_button")
        self.change_password_button = QtWidgets.QPushButton(parent=self.frame_3)
        self.change_password_button.setGeometry(QtCore.QRect(240, 80, 81, 31))
        self.change_password_button.setStyleSheet("background-color: rgb(224, 224, 224)")
        self.change_password_button.setObjectName("change_password_button")
        self.photo_label = QtWidgets.QLabel(parent=self.frame_3)
        self.photo_label.setGeometry(QtCore.QRect(40, 50, 51, 51))
        self.photo_label.setStyleSheet("background-color: rgb(224, 224, 224)")
        self.photo_label.setObjectName("photo_label")
        self.nickname_label = QtWidgets.QLabel(parent=self.frame_3)
        self.nickname_label.setGeometry(QtCore.QRect(100, 70, 61, 16))
        self.nickname_label.setObjectName("nickname_label")
        
        self.goal_progress = QtWidgets.QProgressBar(parent=self.frame_3)
        self.goal_progress.setGeometry(QtCore.QRect(40, 120, 281, 23))
        # self.goal_progress.setProperty("value", 24)
        self.goal_progress.setObjectName("goal_progress")
        self.goal_progress_label = QtWidgets.QLabel(parent=self.frame_3)
        self.goal_progress_label.setGeometry(QtCore.QRect(123, 180, 131, 16))
        self.goal_progress_label.setObjectName("goal_progress_label")
        self.updateGoalProgress()
        
        self.level_progress = QtWidgets.QProgressBar(parent=self.frame_3)
        self.level_progress.setGeometry(QtCore.QRect(40, 160, 281, 23))
        # self.level_progress.setProperty("value", 24)
        self.level_progress.setObjectName("level_progress")
        self.level_progress_label = QtWidgets.QLabel(parent=self.frame_3)
        self.level_progress_label.setGeometry(QtCore.QRect(110, 140, 141, 16))
        self.level_progress_label.setObjectName("level_progress_label")
        self.updateLevelProgress()
        
        MyPageUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MyPageUI)
        self.statusbar.setObjectName("statusbar")
        MyPageUI.setStatusBar(self.statusbar)

        self.retranslateUi(MyPageUI)
        QtCore.QMetaObject.connectSlotsByName(MyPageUI)

    def retranslateUi(self, MyPageUI):
        _translate = QtCore.QCoreApplication.translate
        MyPageUI.setWindowTitle(_translate("MyPageUI", "MainWindow"))
        self.set_goal_button.setText(_translate("MyPageUI", "목표 등록하기"))
        self.wrong_note_button.setText(_translate("MyPageUI", "오답노트"))
        self.bookmark_note_button.setText(_translate("MyPageUI", "즐겨찾기"))
        self.back_button.setText(_translate("MyPageUI", "뒤로가기"))
        self.menu_name_label.setText(_translate("MyPageUI", "마이페이지"))
        self.home_button.setText(_translate("MyPageUI", "홈"))
        self.logout_button.setText(_translate("MyPageUI", "로그아웃"))
        self.change_password_button.setText(_translate("MyPageUI", "비밀번호 변경"))
        self.photo_label.setText(_translate("MyPageUI", "사진"))
        self.nickname_label.setText(_translate("MyPageUI", self.user.userNickname))
#        self.goal_progress_label.setText(_translate("MyPageUI", "목표 유닛 수             0/0"))
#        self.level_progress_label.setText(_translate("MyPageUI", "강아지 성장까지           0/0"))

    def updateUserNickname(self, newUserNickname):
        self.nickname_label.setText(newUserNickname)

    def updateGoalProgress(self):
        # 목표 진행 상황 게이지 출력
        progress = int((self.user.today_learned_unit / self.user.userGoal) * 100) if self.user.userGoal != 0 else 0
        print(self.user.today_learned_unit, progress)
        self.goal_progress.setValue(progress)
        
        # 금일 학습유닛 진행상황 텍스트 출력
        gageText = "금일 학습유닛  "+str(self.user.today_learned_unit) + "/" + str(self.user.userGoal)
        print(gageText)
        self.goal_progress_label.setText(gageText)

    def updateLevelProgress(self):
        # 개 진행 상황 게이지 출력
        progress = int((self.user.total_learned_unit % 24 / 24) * 100)
        print(self.user.total_learned_unit, progress)
        self.goal_progress.setValue(progress)

        # 택스트 : 토익멍 성장까지   1/24
        gageText = "토익멍 성장까지  "+ str(self.user.total_learned_unit % 24) + "/24"
        print(gageText)
        self.level_progress_label.setText(gageText)
