from PyQt6 import QtWidgets, QtCore
from PyQt6.QtCore import QSize, Qt
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import QHBoxLayout
from dialog.select_test_dialog import SelectTestDialog

# Form implementation generated from reading ui file 'prepare_entire_test_ui.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class PrepareEntireTestUI(object):
    def setupUi(self, PrepareEntireTestUI):
        self.parent = PrepareEntireTestUI

        PrepareEntireTestUI.setObjectName("PrepareEntireTestUI")
        PrepareEntireTestUI.resize(360, 600)
        PrepareEntireTestUI.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=PrepareEntireTestUI)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 480, 361, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet("border: 0px")

        self.start_test_button = QtWidgets.QPushButton(parent=self.frame)
        self.start_test_button.setGeometry(QtCore.QRect(10, 10, 341, 71))
        self.start_test_button.setStyleSheet("background-color: rgb(255, 230, 130)")
        self.start_test_button.setObjectName("start_test_button")
        self.start_test_button.clicked.connect(self.showPopUp)

        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 360, 60))
        self.frame_2.setStyleSheet("background-color: rgba(253, 213, 51, 0.97)")
        
        # self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        # self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        # self.frame_2.setObjectName("frame_2")
        # self.frame_2.setStyleSheet("border: 0px")

        self.back_button = QtWidgets.QPushButton("←")
        self.back_button.setFixedSize(QSize(50, 50))
        self.back_button.clicked.connect(lambda: self.closeAndOpen("back"))

        self.menu_name_label = QtWidgets.QLabel("테스트 시작하기")
        self.menu_name_label.setFont(QFont("Han Sans", 20))
        self.menu_name_label.setFixedSize(QSize(240, 60))
        self.menu_name_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.menu_name_label.setObjectName("menu_name_label")

        self.home_button = QtWidgets.QPushButton("🏠")
        self.home_button.setFixedSize(QSize(50, 50))
        self.home_button.clicked.connect(lambda: self.closeAndOpen("home"))

        top_layout = QHBoxLayout()
        top_layout.addWidget(self.back_button, alignment=Qt.AlignmentFlag.AlignLeft)
        top_layout.addWidget(self.menu_name_label)
        top_layout.addWidget(self.home_button, alignment=Qt.AlignmentFlag.AlignRight)

        self.frame_2.setLayout(top_layout)

        # self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.frame_2)
        # self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 361, 61))
        # self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        # self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        # self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout.setObjectName("horizontalLayout")
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        # self.back_button.setSizePolicy(sizePolicy)
        # self.back_button.setObjectName("back_button")
        # self.back_button.clicked.connect(lambda: self.closeAndOpen("back"))
        # self.horizontalLayout.addWidget(self.back_button)
        
#         self.menu_name_label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.menu_name_label.sizePolicy().hasHeightForWidth())
#         self.menu_name_label.setSizePolicy(sizePolicy)
#         self.menu_name_label.setStyleSheet("font: 24px bold;\n"
# "qproperty-alignment: \'AlignCenter\';\n"
# "text-align: center")
#         self.menu_name_label.setObjectName("menu_name_label")
#         self.horizontalLayout.addWidget(self.menu_name_label)
#         self.home_button = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
#         sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
#         sizePolicy.setHorizontalStretch(0)
#         sizePolicy.setVerticalStretch(0)
#         sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
#         self.home_button.setSizePolicy(sizePolicy)
#         self.home_button.setObjectName("home_button")
#         self.home_button.clicked.connect(lambda: self.closeAndOpen("home"))
        # self.horizontalLayout.addWidget(self.home_button)
        
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 280, 361, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setStyleSheet("border: 0px")

        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(360, 0, 361, 191))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_4.setStyleSheet("border: 0px")

        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setGeometry(QtCore.QRect(110, 60, 141, 16))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame_3)
        self.comboBox.setGeometry(QtCore.QRect(110, 90, 131, 31))
        self.comboBox.setStyleSheet("color: black;\n"
"background: transparent;\n"
"border: 1px solid rgb(190, 190, 190);\n"
"border-radius: 8px;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(0, 60, 361, 221))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_5.setStyleSheet("border: 0px")

        self.frame_6 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(360, 0, 361, 191))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_6.setStyleSheet("border: 0px")

        self.frame_7 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_7.setGeometry(QtCore.QRect(30, 20, 301, 181))
        self.frame_7.setStyleSheet("background-color: rgb(224, 224, 224);\n"
"border: 0px")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")

        self.inform_label = QtWidgets.QTextBrowser(parent=self.frame_7)
        self.inform_label.setGeometry(QtCore.QRect(30, 30, 241, 111))
        self.inform_label.setObjectName("inform_label")
        PrepareEntireTestUI.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=PrepareEntireTestUI)
        self.statusbar.setObjectName("statusbar")
        PrepareEntireTestUI.setStatusBar(self.statusbar)

        self.retranslateUi(PrepareEntireTestUI)
        QtCore.QMetaObject.connectSlotsByName(PrepareEntireTestUI)

    def retranslateUi(self, PrepareEntireTestUI):
        _translate = QtCore.QCoreApplication.translate
        PrepareEntireTestUI.setWindowTitle(_translate("PrepareEntireTestUI", "MainWindow"))
        self.start_test_button.setText(_translate("PrepareEntireTestUI", "테스트 시작하기"))
        # self.back_button.setText(_translate("PrepareEntireTestUI", "뒤로가기"))
        self.menu_name_label.setText(_translate("PrepareEntireTestUI", "테스트 시작하기"))
        # self.home_button.setText(_translate("PrepareEntireTestUI", "홈"))
        self.label.setText(_translate("PrepareEntireTestUI", "모의고사를 실시할 단어 수"))
        self.comboBox.setItemText(0, _translate("PrepareEntireTestUI", "10"))
        self.comboBox.setItemText(1, _translate("PrepareEntireTestUI", "20"))
        self.comboBox.setItemText(2, _translate("PrepareEntireTestUI", "30"))
        self.comboBox.setItemText(3, _translate("PrepareEntireTestUI", "40"))
        self.comboBox.setItemText(4, _translate("PrepareEntireTestUI", "50"))
        self.inform_label.setHtml(_translate("PrepareEntireTestUI", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">테스트 시작하기에서는</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">전체 유닛의 1200개 단어에 대해</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">모의고사를 실시합니다</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">모의고사를 실시할 단어의 개수를</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">직접 지정할 수 있습니다</span></p></body></html>"))

    def showPopUp(self) :
        popup = SelectTestDialog(self, self.parent)
        popup.exec()

    def closeAndOpen(self, option) :
        if option == "back" :
            self.parent.back_button_clicked()
        elif option == "home" :
            self.parent.home_button_clicked()
        elif option == "test" :
            self.parent.pushButton_clicked()
        else :
            print("잘못된 입력입니다.")