# Form implementation generated from reading ui file 'ui_review_test.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 887)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(150, 10, 360, 581))
        self.frame.setMaximumSize(QtCore.QSize(360, 600))
        self.frame.setStyleSheet("background-color: white ;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 360, 60))
        self.label.setMaximumSize(QtCore.QSize(360, 60))
        self.label.setStyleSheet("background-color : rgba(253, 213, 51, 0.97) ;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.go_back_but = QtWidgets.QPushButton(parent=self.frame)
        self.go_back_but.setGeometry(QtCore.QRect(0, 0, 60, 60))
        self.go_back_but.setMaximumSize(QtCore.QSize(60, 60))
        self.go_back_but.setStyleSheet("background-color: rgba(253, 213, 51, 0.97) ;\n"
"")
        self.go_back_but.setObjectName("go_back_but")
        self.home_but = QtWidgets.QPushButton(parent=self.frame)
        self.home_but.setGeometry(QtCore.QRect(300, 0, 60, 60))
        self.home_but.setMaximumSize(QtCore.QSize(60, 60))
        self.home_but.setStyleSheet("background-color: rgba(253, 213, 51, 0.97) ;\n"
"")
        self.home_but.setObjectName("home_but")
        self.page_name = QtWidgets.QLabel(parent=self.frame)
        self.page_name.setGeometry(QtCore.QRect(60, 0, 240, 60))
        self.page_name.setMaximumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.page_name.setFont(font)
        self.page_name.setStyleSheet("background-color : rgba(253, 213, 51, 0.97) ;")
        self.page_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.page_name.setObjectName("page_name")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(0, 60, 360, 45))
        self.frame_3.setMaximumSize(QtCore.QSize(360, 45))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.line = QtWidgets.QFrame(parent=self.frame_3)
        self.line.setGeometry(QtCore.QRect(0, 30, 365, 16))
        self.line.setMaximumSize(QtCore.QSize(365, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        self.line.setFont(font)
