# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ui_review_testxJPKbs.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenuBar, QPushButton, QSizePolicy, QStatusBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1020, 887)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(150, 10, 360, 581))
        self.frame.setMaximumSize(QSize(360, 600))
        self.frame.setStyleSheet(u"background-color: white ;")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 0, 360, 60))
        self.label.setMaximumSize(QSize(360, 60))
        self.label.setStyleSheet(u"background-color : rgba(253, 213, 51, 0.97) ;")
        self.go_back_but = QPushButton(self.frame)
        self.go_back_but.setObjectName(u"go_back_but")
        self.go_back_but.setGeometry(QRect(0, 0, 60, 60))
        self.go_back_but.setMaximumSize(QSize(60, 60))
        self.go_back_but.setStyleSheet(u"background-color: rgba(253, 213, 51, 0.97) ;\n"
"")
        self.home_but = QPushButton(self.frame)
        self.home_but.setObjectName(u"home_but")
        self.home_but.setGeometry(QRect(300, 0, 60, 60))
        self.home_but.setMaximumSize(QSize(60, 60))
        self.home_but.setStyleSheet(u"background-color: rgba(253, 213, 51, 0.97) ;\n"
"")
        self.page_name = QLabel(self.frame)
        self.page_name.setObjectName(u"page_name")
        self.page_name.setGeometry(QRect(60, 0, 240, 60))
        self.page_name.setMaximumSize(QSize(240, 60))
        font = QFont()
        font.setPointSize(20)
        self.page_name.setFont(font)
        self.page_name.setStyleSheet(u"background-color : rgba(253, 213, 51, 0.97) ;")
        self.page_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 60, 360, 45))
        self.frame_3.setMaximumSize(QSize(360, 45))
        self.frame_3.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Shadow.Raised)
        self.line = QFrame(self.frame_3)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 30, 365, 16))
        self.line.setMaximumSize(QSize(365, 16777215))
        font1 = QFont()
        font1.setBold(False)
        self.line.setFont(font1)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.unit_name = QLabel(self.frame_3)
        self.unit_name.setObjectName(u"unit_name")
        self.unit_name.setGeometry(QRect(0, 10, 48, 21))
        self.unit_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frame_2 = QFrame(self.frame_3)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(270, 10, 91, 16))
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.label_2 = QLabel(self.frame_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(0, 0, 16, 16))
        self.label_2.setStyleSheet(u"color : blue")
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6 = QLabel(self.frame_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(50, 0, 16, 16))
        self.label_6.setStyleSheet(u"Color : red ;")
        self.label_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.q_right = QLabel(self.frame_2)
        self.q_right.setObjectName(u"q_right")
        self.q_right.setGeometry(QRect(20, 0, 16, 16))
        self.q_right.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.q_wrong = QLabel(self.frame_2)
        self.q_wrong.setObjectName(u"q_wrong")
        self.q_wrong.setGeometry(QRect(70, 0, 16, 16))
        self.q_wrong.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_6.raise_()
        self.q_right.raise_()
        self.q_wrong.raise_()
        self.label_2.raise_()
        self.q_num = QLabel(self.frame)
        self.q_num.setObjectName(u"q_num")
        self.q_num.setGeometry(QRect(0, 100, 48, 31))
        font2 = QFont()
        font2.setPointSize(11)
        self.q_num.setFont(font2)
        self.q_num.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line_2 = QFrame(self.frame)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 260, 365, 16))
        self.line_2.setMaximumSize(QSize(365, 16777215))
        self.line_2.setFont(font1)
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.frame_5 = QFrame(self.frame)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 280, 360, 300))
        self.frame_5.setMaximumSize(QSize(360, 300))
        self.frame_5.setStyleSheet(u"background-color : white ;")
        self.frame_5.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Shadow.Raised)
        self.ans_1 = QPushButton(self.frame_5)
        self.ans_1.setObjectName(u"ans_1")
        self.ans_1.setGeometry(QRect(20, 0, 150, 100))
        self.ans_1.setMaximumSize(QSize(150, 100))
        self.ans_1.setFont(font)
        self.ans_1.setStyleSheet(u"background-color : rgb(255, 230, 130) ;")
        self.ans_2 = QPushButton(self.frame_5)
        self.ans_2.setObjectName(u"ans_2")
        self.ans_2.setGeometry(QRect(190, 0, 150, 100))
        self.ans_2.setMaximumSize(QSize(150, 100))
        self.ans_2.setFont(font)
        self.ans_2.setStyleSheet(u"background-color : rgb(255, 230, 130) ;")
        self.ans_3 = QPushButton(self.frame_5)
        self.ans_3.setObjectName(u"ans_3")
        self.ans_3.setGeometry(QRect(20, 120, 150, 100))
        self.ans_3.setMaximumSize(QSize(150, 100))
        self.ans_3.setFont(font)
        self.ans_3.setStyleSheet(u"background-color : rgb(255, 230, 130) ;")
        self.ans_4 = QPushButton(self.frame_5)
        self.ans_4.setObjectName(u"ans_4")
        self.ans_4.setGeometry(QRect(190, 120, 150, 100))
        self.ans_4.setMaximumSize(QSize(150, 100))
        self.ans_4.setFont(font)
        self.ans_4.setStyleSheet(u"background-color : rgb(255, 230, 130) ;")
        self.look_ans = QPushButton(self.frame_5)
        self.look_ans.setObjectName(u"look_ans")
        self.look_ans.setGeometry(QRect(20, 230, 320, 60))
        self.look_ans.setMaximumSize(QSize(320, 60))
        self.look_ans.setFont(font)
        self.look_ans.setStyleSheet(u"background-color : rgb(224, 224, 224) ;")
        self.frame_6 = QFrame(self.frame)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(0, 150, 360, 111))
        self.frame_6.setMaximumSize(QSize(360, 120))
        self.frame_6.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Shadow.Raised)
        self.q_name = QLabel(self.frame_6)
        self.q_name.setObjectName(u"q_name")
        self.q_name.setGeometry(QRect(0, 0, 360, 60))
        self.q_name.setMaximumSize(QSize(360, 60))
        font3 = QFont()
        font3.setPointSize(30)
        font3.setBold(True)
        self.q_name.setFont(font3)
        self.q_name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ans_meaning = QLabel(self.frame_6)
        self.ans_meaning.setObjectName(u"ans_meaning")
        self.ans_meaning.setGeometry(QRect(60, 50, 240, 30))
        self.ans_meaning.setMaximumSize(QSize(240, 30))
        font4 = QFont()
        font4.setPointSize(12)
        self.ans_meaning.setFont(font4)
        self.ans_meaning.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.ans_sentence = QLabel(self.frame_6)
        self.ans_sentence.setObjectName(u"ans_sentence")
        self.ans_sentence.setGeometry(QRect(60, 80, 240, 30))
        self.ans_sentence.setMaximumSize(QSize(240, 30))
        font5 = QFont()
        font5.setPointSize(10)
        self.ans_sentence.setFont(font5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1020, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.go_back_but.setText(QCoreApplication.translate("MainWindow", u"\ub4a4\ub85c\uac00\uae30", None))
        self.home_but.setText(QCoreApplication.translate("MainWindow", u"\ud648", None))
        self.page_name.setText(QCoreApplication.translate("MainWindow", u"\ubcf5\uc2b5 \ud14c\uc2a4\ud2b8", None))
        self.unit_name.setText(QCoreApplication.translate("MainWindow", u"unit 1", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"O", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.q_right.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.q_wrong.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.q_num.setText(QCoreApplication.translate("MainWindow", u"5\ubc88", None))
        self.ans_1.setText(QCoreApplication.translate("MainWindow", u"Carbon", None))
        self.ans_2.setText(QCoreApplication.translate("MainWindow", u"Cosmos", None))
        self.ans_3.setText(QCoreApplication.translate("MainWindow", u"Carbone", None))
        self.ans_4.setText(QCoreApplication.translate("MainWindow", u"Candidate", None))
        self.look_ans.setText(QCoreApplication.translate("MainWindow", u"\uc815\ub2f5 \ubcf4\uae30", None))
        self.q_name.setText(QCoreApplication.translate("MainWindow", u"\ud0c4\uc18c", None))
        self.ans_meaning.setText(QCoreApplication.translate("MainWindow", u"Carbon", None))
        self.ans_sentence.setText(QCoreApplication.translate("MainWindow", u"Carbon \uad00\ub828 \uc608\ubb38", None))
    # retranslateUi

