# Form implementation generated from reading ui file 'C:\Users\CHO\toicProject\hun\toicPojectSH\member\homePage.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_homePage(object):
    def setupUi(self, homePage):
        homePage.setObjectName("homePage")
        homePage.resize(360, 600)
        homePage.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(parent=homePage)
        self.centralwidget.setObjectName("centralwidget")
        self.menuBase = QtWidgets.QWidget(parent=self.centralwidget)
        self.menuBase.setGeometry(QtCore.QRect(0, 0, 360, 58))
        self.menuBase.setStyleSheet("background-color:rgba(253, 213, 51, 0.97)")
        self.menuBase.setObjectName("menuBase")
        self.titleName = QtWidgets.QLabel(parent=self.menuBase)
        self.titleName.setGeometry(QtCore.QRect(170, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.titleName.setFont(font)
        self.titleName.setStyleSheet("font: 700 20pt \"맑은 고딕\";\n"
"")
        self.titleName.setObjectName("titleName")
        self.toStudyBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.toStudyBtn.setGeometry(QtCore.QRect(60, 340, 240, 40))
        self.toStudyBtn.setStyleSheet("background-color:rgb(255, 240, 129)")
        self.toStudyBtn.setObjectName("toStudyBtn")
        self.toTotalTestBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.toTotalTestBtn.setGeometry(QtCore.QRect(60, 400, 240, 40))
        self.toTotalTestBtn.setStyleSheet("background-color:rgb(255, 240, 129)")
        self.toTotalTestBtn.setObjectName("toTotalTestBtn")
        self.toMyPageBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.toMyPageBtn.setGeometry(QtCore.QRect(60, 460, 240, 40))
        self.toMyPageBtn.setStyleSheet("background-color:rgb(255, 240, 129)")
        self.toMyPageBtn.setObjectName("toMyPageBtn")
        self.totalProgressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.totalProgressBar.setGeometry(QtCore.QRect(40, 280, 311, 16))
        self.totalProgressBar.setProperty("value", 24)
        self.totalProgressBar.setObjectName("totalProgressBar")
        self.todayProgressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.todayProgressBar.setGeometry(QtCore.QRect(40, 310, 311, 16))
        self.todayProgressBar.setProperty("value", 24)
        self.todayProgressBar.setObjectName("todayProgressBar")
        self.studyHelpBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.studyHelpBtn.setGeometry(QtCore.QRect(310, 350, 31, 28))
        self.studyHelpBtn.setStyleSheet("font: 6pt \"맑은 고딕\";")
        self.studyHelpBtn.setObjectName("studyHelpBtn")
        self.totalTestHelpBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.totalTestHelpBtn.setGeometry(QtCore.QRect(310, 410, 31, 28))
        self.totalTestHelpBtn.setStyleSheet("font: 6pt \"맑은 고딕\";")
        self.totalTestHelpBtn.setObjectName("totalTestHelpBtn")
        self.myPageHelpBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.myPageHelpBtn.setGeometry(QtCore.QRect(310, 470, 31, 28))
        self.myPageHelpBtn.setStyleSheet("font: 6pt \"맑은 고딕\";")
        self.myPageHelpBtn.setObjectName("myPageHelpBtn")
        homePage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=homePage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 26))
        self.menubar.setObjectName("menubar")
        homePage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=homePage)
        self.statusbar.setObjectName("statusbar")
        homePage.setStatusBar(self.statusbar)

        self.retranslateUi(homePage)
        QtCore.QMetaObject.connectSlotsByName(homePage)

    def retranslateUi(self, homePage):
        _translate = QtCore.QCoreApplication.translate
        homePage.setWindowTitle(_translate("homePage", "MainWindow"))
        self.titleName.setText(_translate("homePage", "홈"))
        self.toStudyBtn.setText(_translate("homePage", "학습하기"))
        self.toTotalTestBtn.setText(_translate("homePage", "테스트 시작하기"))
        self.toMyPageBtn.setText(_translate("homePage", "마이페이지"))
        self.studyHelpBtn.setText(_translate("homePage", "도움말"))
        self.totalTestHelpBtn.setText(_translate("homePage", "도움말"))
        self.myPageHelpBtn.setText(_translate("homePage", "도움말"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homePage = QtWidgets.QMainWindow()
    ui = Ui_homePage()
    ui.setupUi(homePage)
    homePage.show()
    sys.exit(app.exec())
