# Form implementation generated from reading ui file 'C:\Users\CHO\toicProject\hun\toicPojectSH\member\partPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again. Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_partPage(object):
    def setupUi(self, partPage):
        partPage.setObjectName("partPage")
        partPage.resize(360, 600)
        partPage.setStyleSheet("background-color:rgb(255, 255, 255)")

        self.centralwidget = QtWidgets.QWidget(parent=partPage)
        self.centralwidget.setObjectName("centralwidget")

        self.menuBase = QtWidgets.QWidget(parent=self.centralwidget)
        self.menuBase.setGeometry(QtCore.QRect(0, 0, 360, 58))
        self.menuBase.setStyleSheet("background-color:rgba(253, 213, 51, 0.97)")
        self.menuBase.setObjectName("menuBase")

        self.titleName = QtWidgets.QLabel(parent=self.menuBase)
        self.titleName.setGeometry(QtCore.QRect(130, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        self.titleName.setFont(font)
        self.titleName.setStyleSheet("font: 700 20pt \"맑은 고딕\";")
        self.titleName.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.titleName.setObjectName("titleName")

        self.backBtn = QtWidgets.QPushButton(parent=self.menuBase)
        self.backBtn.setGeometry(QtCore.QRect(0, 0, 60, 60))
        self.backBtn.setObjectName("backBtn")

        self.homeBtn = QtWidgets.QPushButton(parent=self.menuBase)
        self.homeBtn.setGeometry(QtCore.QRect(300, 0, 60, 60))
        self.homeBtn.setObjectName("homeBtn")

        # Create buttons using a loop
        self.showUnitPageBtns = []
        for i in range(1, 11):
            button = QtWidgets.QPushButton(parent=self.centralwidget)
            button.setGeometry(QtCore.QRect(10 + ((i+1) % 2) * 170, 70 + ((i-1) // 2) * 100, 161, 91))
            button.setStyleSheet("background-color:rgb(193, 193, 193);\nfont: 22pt \"맑은 고딕\";")
            button.setObjectName(f"showUnitPageBtn_{i}")
            self.showUnitPageBtns.append(button)

        partPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=partPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 33))
        self.menubar.setObjectName("menubar")
        partPage.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=partPage)
        self.statusbar.setObjectName("statusbar")
        partPage.setStatusBar(self.statusbar)

        self.retranslateUi(partPage)
        QtCore.QMetaObject.connectSlotsByName(partPage)

    def retranslateUi(self, partPage):
        _translate = QtCore.QCoreApplication.translate
        partPage.setWindowTitle(_translate("partPage", "MainWindow"))
        self.titleName.setText(_translate("partPage", "학습하기"))
        self.backBtn.setText(_translate("partPage", "뒤로가기"))
        self.homeBtn.setText(_translate("partPage", "홈"))
        for i, button in enumerate(self.showUnitPageBtns, 1):
            button.setText(_translate("partPage", f"Part {i}"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    partPage = QtWidgets.QMainWindow()
    ui = Ui_partPage()
    ui.setupUi(partPage)
    partPage.show()
    sys.exit(app.exec())