# Form implementation generated from reading ui file 'C:\Users\CHO\toicProject\hun\toicPojectSH\member\unitPage.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_unitPage(object):
    def setupUi(self, unitPage):
        unitPage.setObjectName("unitPage")
        unitPage.resize(360, 608)
        unitPage.setStyleSheet("background-color:rgb(255, 255, 255)")

        self.centralwidget = QtWidgets.QWidget(parent=unitPage)
        self.centralwidget.setObjectName("centralwidget")

        self.menuBase = QtWidgets.QWidget(parent=self.centralwidget)
        self.menuBase.setGeometry(QtCore.QRect(0, 0, 360, 58))
        self.menuBase.setStyleSheet("background-color:rgba(253, 213, 51, 0.97)")
        self.menuBase.setObjectName("menuBase")

        self.titleName = QtWidgets.QLabel(parent=self.menuBase)
        self.titleName.setGeometry(QtCore.QRect(130, 10, 131, 41))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(20)
        font.setBold(True)
        self.titleName.setFont(font)
        self.titleName.setStyleSheet("font: 700 20pt \"맑은 고딕\";")
        self.titleName.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.titleName.setObjectName("titleName")

        self.backBtn = QtWidgets.QPushButton(parent=self.menuBase)
        self.backBtn.setGeometry(QtCore.QRect(0, 0, 60, 60))
        self.backBtn.setObjectName("backBtn")

        self.homeBtn = QtWidgets.QPushButton(parent=self.menuBase)
        self.homeBtn.setGeometry(QtCore.QRect(300, 0, 60, 60))
        self.homeBtn.setObjectName("homeBtn")

        # Create buttons using a loop
        self.unitButtons = []
        for i in range(1, 15):
            button = QtWidgets.QPushButton(parent=self.centralwidget)
            button.setGeometry(QtCore.QRect(10 + ((i+1) % 2) * 170, 70 + ((i-1) // 2) * 100, 161, 91))
            button.setStyleSheet("background-color:rgb(193, 193, 193);\nfont: 22pt \"맑은 고딕\";")
            button.setObjectName(f"unitButton_{i}")
            self.unitButtons.append(button)

        unitPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=unitPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 33))
        self.menubar.setObjectName("menubar")
        unitPage.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=unitPage)
        self.statusbar.setObjectName("statusbar")
        unitPage.setStatusBar(self.statusbar)

        self.retranslateUi(unitPage)
        QtCore.QMetaObject.connectSlotsByName(unitPage)

    def retranslateUi(self, unitPage):
        _translate = QtCore.QCoreApplication.translate
        unitPage.setWindowTitle(_translate("unitPage", "MainWindow"))
        self.titleName.setText(_translate("unitPage", "학습하기"))
        self.backBtn.setText(_translate("unitPage", "뒤로가기"))
        self.homeBtn.setText(_translate("unitPage", "홈"))
        for i, button in enumerate(self.unitButtons, 1):
            button.setText(_translate("unitPage", f"Unit {i}"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    unitPage = QtWidgets.QMainWindow()
    ui = Ui_unitPage()
    ui.setupUi(unitPage)
    unitPage.show()
    sys.exit(app.exec())